# syntax=docker/dockerfile:1.4
FROM --platform=linux/386 python:3.10-alpine AS builder
WORKDIR /code
COPY requirements.txt /code
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -U flask-cors
COPY . .

ENV FLASK_APP app.py
ENV FLASK_ENV DEV
ENV FLASK_RUN_PORT 5000
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 5000

CMD ["flask", "run"]

FROM builder AS dev-envs

RUN apk update
RUN apk add git

RUN addgroup -S docker
RUN adduser -S --shell /bin/bash --ingroup docker vscode

# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /

CMD ["flask", "run", "--host","0.0.0.0"]